// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVHuR41ArDFAFtutmDNm_91TrxYr2jqI',
    appId: '1:742288804:android:7dc17fdd2ef92be1aee531',
    messagingSenderId: '742288804',
    projectId: 'hew-a-38090',
    storageBucket: 'hew-a-38090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0iiATosFvLB1hRLXIRF-DouBAt83-e8',
    appId: '1:742288804:ios:e8562ae62e46ac9daee531',
    messagingSenderId: '742288804',
    projectId: 'hew-a-38090',
    storageBucket: 'hew-a-38090.appspot.com',
    iosClientId: '742288804-b93dderu2s6al71f8b395br1vo4t7fm8.apps.googleusercontent.com',
    iosBundleId: 'com.se.hewa',
  );
}
